name: 16 Environments
run-name: 16 Environments | env - ${{inputs.target-env}}

on:
      
    workflow_dispatch:
      inputs:
        debug:
          type: boolean
          default: false
        target-env:
            type: environment
            default: staging

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.target-env}}
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'devault value'}}
        steps:
            - name: Ech vars
              run: | 
                echo "Env variable: ${{env.my-env-value}}"