name: 17 Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS 
on:
      
    workflow_dispatch:
      inputs:
        debug:
          type: boolean
          default: false
jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6
                with:
                    ref: ${{ github.head_ref }}
            -   name: Check for Dependency Updates
                uses: ./.github/actions/js-dependency-update

