name: 17 Custom Actions - Docker
run-name: 17 - 3 - Custom Actions - Docker
on:
      
    workflow_dispatch:
      inputs:
        debug:
          type: boolean
          default: false
        url:
            type: choice
            options:
              - 'https://www.google.com'
              - 'https://www.invalid-aaslnasedaishdakj.com'
              - 'invalid-aaslnasedaishdakj'

        max_trials:
            description: Maximum number of trials until action fails.
            default: '10'
            required: false
        delay:
            description: Dalay in seconds between trials
            default: '5'
            required: false


        # working-dir:
        #     type: string
        #     default: 17-custom-actions/react-app


jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6
                with:
                    ref: ${{ github.head_ref }}
            -   name: Ping URL
                uses: ./.github/actions/docker-ping-url
                with:
                    url: ${{inputs.url}}
                    max_trials: ${{inputs.max_trials}}
                    delay: ${{inputs.delay}}
